-- DCAL Vercel/Supabase foundation.
-- Clinical pages remain private. Human users authenticate through Supabase Auth;
-- authorization comes only from public.profiles.role/active, never user metadata.

create schema if not exists dcal_private;
revoke all on schema dcal_private from public, anon;
grant usage on schema dcal_private to authenticated;

do $$
begin
  create type public.dcal_member_role as enum ('annotator', 'reviewer', 'admin');
exception
  when duplicate_object then null;
end
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Pending user'
    check (char_length(btrim(display_name)) between 1 and 100),
  role public.dcal_member_role not null default 'annotator',
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  ingestion_key text not null unique
    check (ingestion_key ~ '^task_[0-9a-f]{32}$'),
  source_origin text not null
    check (source_origin in ('manual_upload', 'google_drive')),
  dataset_eligible boolean not null default false,
  source_object_id text not null,
  source_sha256 text not null unique
    check (source_sha256 ~ '^[0-9a-f]{64}$'),
  raw_source_sha256 text
    check (raw_source_sha256 is null or raw_source_sha256 ~ '^[0-9a-f]{64}$'),
  patient_group_id text,
  encounter_group_id text,
  writer_group_ids jsonb not null default '[]'::jsonb
    check (jsonb_typeof(writer_group_ids) = 'array'),
  source_page_index integer not null default 1
    check (source_page_index > 0),
  ingestion_schema_version text,
  render_profile text not null,
  storage_bucket text not null default 'dcal-pages'
    check (storage_bucket = 'dcal-pages'),
  storage_path text not null unique
    check (storage_path !~ '(^|/)\.\.(/|$)'),
  image_width integer not null check (image_width > 0),
  image_height integer not null check (image_height > 0),
  status text not null default 'unassigned'
    check (status in ('unassigned', 'in_progress', 'completed', 'needs_review')),
  assigned_to uuid references public.profiles(id) on delete set null,
  assigned_to_name text,
  annotation jsonb not null default jsonb_build_object(
    'schema_version', 'dcal.annotation.v2',
    'document_type', null,
    'document_variant', null,
    'content_profile', null,
    'image_quality', jsonb_build_array(),
    'notes', '',
    'regions', jsonb_build_array()
  ),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint tasks_annotation_shape check (
    jsonb_typeof(annotation) = 'object'
    and annotation ->> 'schema_version' = 'dcal.annotation.v2'
    and jsonb_typeof(annotation -> 'regions') = 'array'
    and jsonb_typeof(annotation -> 'image_quality') = 'array'
  ),
  constraint tasks_provenance_bundle check (
    (
      source_origin = 'manual_upload'
      and dataset_eligible = false
      and patient_group_id is null
      and encounter_group_id is null
      and ingestion_schema_version is null
    )
    or
    (
      source_origin = 'google_drive'
      and dataset_eligible = true
      and patient_group_id is not null
      and encounter_group_id is not null
      and raw_source_sha256 is not null
      and ingestion_schema_version = 'dcal.ingestion.v1'
    )
  )
);

create table public.revisions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  version integer not null check (version > 1),
  actor_user_id uuid references public.profiles(id) on delete set null,
  actor_name text not null check (char_length(btrim(actor_name)) between 1 and 100),
  action text not null check (action in ('save', 'complete')),
  annotation jsonb not null,
  created_at timestamptz not null default now(),
  unique (task_id, version)
);

create index tasks_status_updated_idx on public.tasks(status, updated_at desc);
create index tasks_document_type_idx on public.tasks((annotation ->> 'document_type'));
create index tasks_dataset_eligible_idx on public.tasks(dataset_eligible)
  where dataset_eligible = true;
create index revisions_task_created_idx on public.revisions(task_id, created_at desc);
create index tasks_assigned_to_idx on public.tasks(assigned_to)
  where assigned_to is not null;
create index revisions_actor_user_idx on public.revisions(actor_user_id)
  where actor_user_id is not null;

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.revisions enable row level security;

create or replace function dcal_private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, display_name)
  values (
    new.id,
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''), 'Pending user')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists dcal_auth_user_created on auth.users;
create trigger dcal_auth_user_created
  after insert on auth.users
  for each row execute function dcal_private.handle_new_user();

create or replace function dcal_private.is_active_member(member_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = member_id and active = true
  );
$$;

revoke all on function dcal_private.is_active_member(uuid) from public, anon, authenticated;
grant execute on function dcal_private.is_active_member(uuid) to service_role;

create policy profiles_select_self
on public.profiles
for select
to authenticated
using (id = (select auth.uid()));

-- All task and revision access is intentionally mediated by authenticated
-- Vercel route handlers using the server-only secret key.
create policy tasks_deny_direct_data_api
on public.tasks
for all
to anon, authenticated
using (false)
with check (false);

create policy revisions_deny_direct_data_api
on public.revisions
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.profiles, public.tasks, public.revisions from anon;
revoke all on table public.profiles, public.tasks, public.revisions from authenticated;
grant select on table public.profiles to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'dcal-pages',
  'dcal-pages',
  false,
  26214400,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.dcal_create_manual_task(
  p_actor_user_id uuid,
  p_source_sha256 text,
  p_raw_source_sha256 text,
  p_storage_path text,
  p_image_width integer,
  p_image_height integer
)
returns table(task_id bigint, created boolean, dataset_eligible boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := p_actor_user_id;
  v_task_id bigint;
  v_created boolean := false;
  v_eligible boolean := false;
begin
  if v_user_id is null or not dcal_private.is_active_member(v_user_id) then
    raise exception 'active DCAL membership required' using errcode = '42501';
  end if;
  if p_source_sha256 !~ '^[0-9a-f]{64}$'
     or p_raw_source_sha256 !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid source checksum' using errcode = '22023';
  end if;
  if p_image_width < 1 or p_image_height < 1 then
    raise exception 'invalid image dimensions' using errcode = '22023';
  end if;
  if p_storage_path not like ('pilot/' || v_user_id::text || '/%')
     or p_storage_path ~ '(^|/)\.\.(/|$)' then
    raise exception 'invalid pilot storage path' using errcode = '22023';
  end if;
  if not exists (
    select 1 from storage.objects
    where bucket_id = 'dcal-pages' and name = p_storage_path
  ) then
    raise exception 'uploaded page object is missing' using errcode = '22023';
  end if;

  insert into public.tasks(
    ingestion_key,
    source_origin,
    dataset_eligible,
    source_object_id,
    source_sha256,
    raw_source_sha256,
    source_page_index,
    render_profile,
    storage_path,
    image_width,
    image_height
  ) values (
    'task_' || substring(p_source_sha256 from 1 for 32),
    'manual_upload',
    false,
    'manual_' || substring(p_source_sha256 from 1 for 32),
    p_source_sha256,
    p_raw_source_sha256,
    1,
    'dcal.browser-image.v1',
    p_storage_path,
    p_image_width,
    p_image_height
  )
  on conflict (source_sha256) do nothing
  returning id, public.tasks.dataset_eligible
  into v_task_id, v_eligible;

  if v_task_id is not null then
    v_created := true;
  else
    select id, public.tasks.dataset_eligible
    into v_task_id, v_eligible
    from public.tasks
    where source_sha256 = p_source_sha256;
  end if;

  return query select v_task_id, v_created, v_eligible;
end;
$$;

revoke all on function public.dcal_create_manual_task(uuid, text, text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.dcal_create_manual_task(uuid, text, text, text, integer, integer)
  to service_role;

create or replace function public.dcal_save_task(
  p_actor_user_id uuid,
  p_task_id bigint,
  p_expected_version integer,
  p_annotation jsonb,
  p_status text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := p_actor_user_id;
  v_actor_name text;
  v_current_version integer;
  v_current_status text;
  v_next_status text;
  v_completed_at timestamptz;
begin
  select display_name
  into v_actor_name
  from public.profiles
  where id = v_user_id and active = true;
  if v_actor_name is null then
    raise exception 'active DCAL membership required' using errcode = '42501';
  end if;
  if p_expected_version is null or p_expected_version < 1 then
    raise exception 'expected version must be positive' using errcode = '22023';
  end if;
  if p_status is not null
     and p_status not in ('unassigned', 'in_progress', 'completed', 'needs_review') then
    raise exception 'invalid task status' using errcode = '22023';
  end if;
  if jsonb_typeof(p_annotation) <> 'object'
     or p_annotation ->> 'schema_version' <> 'dcal.annotation.v2'
     or jsonb_typeof(p_annotation -> 'regions') <> 'array'
     or jsonb_typeof(p_annotation -> 'image_quality') <> 'array' then
    raise exception 'invalid annotation shape' using errcode = '22023';
  end if;
  if p_status = 'completed' then
    if nullif(p_annotation ->> 'document_type', '') is null
       or nullif(p_annotation ->> 'content_profile', '') is null then
      raise exception 'document type and content profile are required' using errcode = '22023';
    end if;
    if jsonb_array_length(p_annotation -> 'regions') = 0
       and (p_annotation ->> 'document_type') not in (
         'blank_or_noninformative_page',
         'duplicate_or_rephotographed_source',
         'non_clinical_cover',
         'billing_or_administrative_page',
         'unknown_document'
       ) then
      raise exception 'clinical pages require an annotated region' using errcode = '22023';
    end if;
  end if;

  select version, status
  into v_current_version, v_current_status
  from public.tasks
  where id = p_task_id
  for update;
  if not found then
    raise exception 'task not found' using errcode = 'P0002';
  end if;
  if v_current_version <> p_expected_version then
    raise exception 'this page was changed elsewhere; reload before saving'
      using errcode = '40001';
  end if;

  v_next_status := coalesce(
    p_status,
    case
      when v_current_status in ('unassigned', 'completed') then 'in_progress'
      else v_current_status
    end
  );
  v_completed_at := case when v_next_status = 'completed' then now() else null end;

  update public.tasks
  set annotation = p_annotation,
      status = v_next_status,
      assigned_to = v_user_id,
      assigned_to_name = v_actor_name,
      version = p_expected_version + 1,
      updated_at = now(),
      completed_at = v_completed_at
  where id = p_task_id;

  insert into public.revisions(
    task_id,
    version,
    actor_user_id,
    actor_name,
    action,
    annotation
  ) values (
    p_task_id,
    p_expected_version + 1,
    v_user_id,
    v_actor_name,
    case when p_status = 'completed' then 'complete' else 'save' end,
    p_annotation
  );

  return p_task_id;
end;
$$;

revoke all on function public.dcal_save_task(uuid, bigint, integer, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.dcal_save_task(uuid, bigint, integer, jsonb, text)
  to service_role;

comment on table public.tasks is
  'Mutable DCAL annotation work state; not a frozen dataset release.';
comment on table public.revisions is
  'Append-only human annotation revisions created by dcal_save_task.';
comment on function public.dcal_save_task(uuid, bigint, integer, jsonb, text) is
  'Atomically saves a validated DCAL annotation using optimistic locking.';
