-- Optional annotator-supplied writer identity.
--
-- Nothing in the intake path knows who wrote on a page (D-023), so the writer
-- is recorded by the annotator from the visible signature. A signature names a
-- real clinician, so the readable label stays in this operational registry and
-- only an opaque identifier reaches annotation state and gold export -- the
-- same separation patient and encounter grouping already use (D-006, D-010).

create table public.writers (
  id bigint generated by default as identity primary key,
  writer_group_id text not null unique
    check (writer_group_id ~ '^wri_[A-Za-z0-9_-]{20,64}$'),
  display_label text not null unique
    check (char_length(btrim(display_label)) between 1 and 120),
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index writers_active_idx on public.writers(active) where active = true;

alter table public.writers enable row level security;

create policy writers_deny_direct_data_api
on public.writers
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.writers from anon, authenticated;

comment on table public.writers is
  'Operational registry mapping an opaque writer_group_id to a human-readable '
  'label. Labels name real clinicians and must never be exported to gold.';

create or replace function public.dcal_create_writer(
  p_actor_user_id uuid,
  p_display_label text
)
returns table(writer_group_id text, display_label text, created boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_label text := btrim(p_display_label);
  v_existing public.writers%rowtype;
  v_id text;
begin
  if not exists (
    select 1 from public.profiles where id = p_actor_user_id and active = true
  ) then
    raise exception 'active DCAL membership required' using errcode = '42501';
  end if;
  if v_label is null or char_length(v_label) < 1 or char_length(v_label) > 120 then
    raise exception 'writer label must contain 1 to 120 characters' using errcode = '22023';
  end if;

  select * into v_existing from public.writers where display_label = v_label;
  if found then
    return query select v_existing.writer_group_id, v_existing.display_label, false;
    return;
  end if;

  -- Random rather than derived from the label: an HMAC of a name is reversible
  -- by guessing names, which would defeat the point of the opaque identifier.
  v_id := 'wri_' || translate(encode(extensions.gen_random_bytes(24), 'base64'), '+/=', '-_');

  insert into public.writers(writer_group_id, display_label, created_by)
  values (v_id, v_label, p_actor_user_id);

  return query select v_id, v_label, true;
end;
$$;

revoke all on function public.dcal_create_writer(uuid, text) from public, anon, authenticated;
grant execute on function public.dcal_create_writer(uuid, text) to service_role;

-- dcal_save_task additionally mirrors annotation-declared writers onto the task
-- row, so gold export and any future split query read one queryable column
-- while the annotation keeps the versioned history of what the annotator said.
create or replace function public.dcal_save_task(
  p_actor_user_id uuid,
  p_task_id bigint,
  p_expected_version integer,
  p_annotation jsonb,
  p_status text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := p_actor_user_id;
  v_actor_name text;
  v_current_version integer;
  v_current_status text;
  v_next_status text;
  v_completed_at timestamptz;
  v_writers jsonb := coalesce(p_annotation -> 'writer_group_ids', '[]'::jsonb);
  v_writer_count integer;
  v_known_count integer;
begin
  select display_name
  into v_actor_name
  from public.profiles
  where id = v_user_id and active = true;
  if v_actor_name is null then
    raise exception 'active DCAL membership required' using errcode = '42501';
  end if;
  if p_expected_version is null or p_expected_version < 1 then
    raise exception 'expected version must be positive' using errcode = '22023';
  end if;
  if p_status is not null
     and p_status not in ('unassigned', 'in_progress', 'completed', 'needs_review') then
    raise exception 'invalid task status' using errcode = '22023';
  end if;
  if jsonb_typeof(p_annotation) <> 'object'
     or p_annotation ->> 'schema_version' <> 'dcal.annotation.v2'
     or jsonb_typeof(p_annotation -> 'regions') <> 'array'
     or jsonb_typeof(p_annotation -> 'image_quality') <> 'array' then
    raise exception 'invalid annotation shape' using errcode = '22023';
  end if;
  if jsonb_typeof(v_writers) <> 'array' then
    raise exception 'writer_group_ids must be an array' using errcode = '22023';
  end if;

  -- Every declared writer must already exist in the registry. An annotation
  -- may not invent grouping identity, exactly as ingestion may not (D-010).
  select count(*) into v_writer_count
  from jsonb_array_elements_text(v_writers);
  select count(distinct w.writer_group_id) into v_known_count
  from public.writers w
  where w.writer_group_id in (select jsonb_array_elements_text(v_writers))
    and w.active = true;
  if v_writer_count > 0 and v_known_count <> (
    select count(distinct value) from jsonb_array_elements_text(v_writers) as t(value)
  ) then
    raise exception 'unknown writer identifier' using errcode = '22023';
  end if;

  if p_status = 'completed' then
    if nullif(p_annotation ->> 'document_type', '') is null
       or nullif(p_annotation ->> 'content_profile', '') is null then
      raise exception 'document type and content profile are required' using errcode = '22023';
    end if;
    if jsonb_array_length(p_annotation -> 'regions') = 0
       and (p_annotation ->> 'document_type') not in (
         'blank_or_noninformative_page',
         'duplicate_or_rephotographed_source',
         'non_clinical_cover',
         'unknown_document'
       ) then
      raise exception 'clinical pages require an annotated region' using errcode = '22023';
    end if;
  end if;

  select version, status
  into v_current_version, v_current_status
  from public.tasks
  where id = p_task_id
  for update;
  if not found then
    raise exception 'task not found' using errcode = 'P0002';
  end if;
  if v_current_version <> p_expected_version then
    raise exception 'this page was changed elsewhere; reload before saving'
      using errcode = '40001';
  end if;

  v_next_status := coalesce(
    p_status,
    case
      when v_current_status in ('unassigned', 'completed') then 'in_progress'
      else v_current_status
    end
  );
  v_completed_at := case when v_next_status = 'completed' then now() else null end;

  update public.tasks
  set annotation = p_annotation,
      writer_group_ids = v_writers,
      status = v_next_status,
      assigned_to = v_user_id,
      assigned_to_name = v_actor_name,
      version = p_expected_version + 1,
      updated_at = now(),
      completed_at = v_completed_at
  where id = p_task_id;

  insert into public.revisions(
    task_id,
    version,
    actor_user_id,
    actor_name,
    action,
    annotation
  ) values (
    p_task_id,
    p_expected_version + 1,
    v_user_id,
    v_actor_name,
    case when p_status = 'completed' then 'complete' else 'save' end,
    p_annotation
  );

  return p_task_id;
end;
$$;

revoke all on function public.dcal_save_task(uuid, bigint, integer, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.dcal_save_task(uuid, bigint, integer, jsonb, text)
  to service_role;
