-- Clinical page access audit.
--
-- public.revisions records who CHANGED an annotation. Nothing recorded who
-- READ a patient page or extracted the dataset, which is the access question
-- an institutional review actually asks. This adds an append-only access log
-- written by the server-only routes that deliver page bytes or gold records.

create table public.page_access (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  actor_name text not null check (char_length(btrim(actor_name)) between 1 and 100),
  actor_role public.dcal_member_role not null,
  action text not null check (action in ('view_image', 'export_gold')),
  task_id bigint references public.tasks(id) on delete set null,
  record_count integer check (record_count is null or record_count >= 0),
  created_at timestamptz not null default now(),
  -- An image view names one page; an export names a record count instead.
  constraint page_access_shape check (
    (action = 'view_image' and task_id is not null and record_count is null)
    or
    (action = 'export_gold' and task_id is null and record_count is not null)
  )
);

create index page_access_created_idx on public.page_access(created_at desc);
create index page_access_actor_idx on public.page_access(actor_user_id, created_at desc);
create index page_access_task_idx on public.page_access(task_id, created_at desc)
  where task_id is not null;

alter table public.page_access enable row level security;

-- Browser roles never read or write the audit log directly. Reviewing it is a
-- deliberate operator action against the database, not an application feature.
create policy page_access_deny_direct_data_api
on public.page_access
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.page_access from anon, authenticated;

create or replace function public.dcal_record_page_access(
  p_actor_user_id uuid,
  p_action text,
  p_task_id bigint default null,
  p_record_count integer default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_name text;
  v_actor_role public.dcal_member_role;
begin
  select display_name, role
  into v_actor_name, v_actor_role
  from public.profiles
  where id = p_actor_user_id and active = true;
  if v_actor_name is null then
    raise exception 'active DCAL membership required' using errcode = '42501';
  end if;

  insert into public.page_access(
    actor_user_id,
    actor_name,
    actor_role,
    action,
    task_id,
    record_count
  ) values (
    p_actor_user_id,
    v_actor_name,
    v_actor_role,
    p_action,
    p_task_id,
    p_record_count
  );
end;
$$;

revoke all on function public.dcal_record_page_access(uuid, text, bigint, integer)
  from public, anon, authenticated;
grant execute on function public.dcal_record_page_access(uuid, text, bigint, integer)
  to service_role;

comment on table public.page_access is
  'Append-only application-level record of clinical page reads and gold exports. '
  'Not tamper-proof against the service key; it evidences routine access, not a breach.';
